<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<PublishSingleFile>true</PublishSingleFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="log4net" Version="3.3.1" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="System.DirectoryServices.Protocols" Version="8.0.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ADWSProxy\ADWSProxy.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="tests.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
